;;; test-cockpit-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; Author: Johannes Mueller <github@johannes-mueller.org>
;; URL: https://github.com/johannes-mueller/test-cockpit.el
;; Version: 0.1.0
;; License: GPLv3
;; SPDX-License-Identifier: GPL-3.0-only

;; This file not is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from test-cockpit.el

(autoload 'test-cockpit-test-project "test-cockpit"
"Test the whole project.
ARGS is the UI state for language specific settings.

(fn &optional ARGS)" t)
(autoload 'test-cockpit-test-module "test-cockpit"
"Test the module of the current buffer.
The exact determination of the model is done by the language specific package.
ARGS is the UI state for language specific settings.

If we are not in a test module buffer, the last module we were in
is tested.

(fn &optional ARGS)" t)
(autoload 'test-cockpit-test-function "test-cockpit"
"Run the test function at point.
The exact determination of the function is done by the language
specific package.  ARGS is the UI state for language specific
settings.

If we are not in a test function, the last module test function we
were in is tested.

(fn &optional ARGS)" t)
(autoload 'test-cockpit-repeat-module "test-cockpit"
"Repeat the module at point when the last test run has been called.
This is useful when you test a certain function, jump out of the
test to fix the issue and then want to run the whole module.
Using this function you can do that without jumping back to the
test code.  If there is no last test module to call, the main
dispatch dialog is invoked." t)
(autoload 'test-cockpit-repeat-function "test-cockpit"
"Repeat the function at point when the last test run has been called.
If there is no last test function to call, the main dispatch
dialog is invoked." t)
(autoload 'test-cockpit-custom-test-command "test-cockpit"
"Run `compile' command interactively to allow a custom test command.
The command run is then stored in as last command of the project
and thus can be repeated using `test-cockpit-repeat-test'." t)
(autoload 'test-cockpit-dynamic-custom-test-command "test-cockpit"
"Run `compile' command for a custom test command.
The command run is determined by COMMAND where
* %P is replaced with the absolute current procject root path
* %F is replaced with the absolute current buffer file path
* %f is replaced with the current buffer file path relative to project root

(fn COMMAND)")
(autoload 'test-cockpit-repeat-test "test-cockpit"
"Repeat the last test if the current project had last test.
If the for the project no test has been run during the current
session, the main dispatch dialog is invoked.

(fn &optional ARGS)" t)
(autoload 'test-cockpit-repeat-interactive-test "test-cockpit"
"Repeat the last interactive test command.
This is not meant to be called directly but as a result the transient dispatch
in order to call the last test action with modified ARGS.

(fn &optional ARGS)" t)
(autoload 'test-cockpit-dape-debug-repeat-test "test-cockpit"
"Repeat the last test action calling the dape debugger, if available." t)
(autoload 'test-cockpit-dispatch "test-cockpit"
"Invoke the user interface of to setup and run tests.
If the repeat suffix has been appended it is removed afterwards
as will be no longer valid and we don't want the suffixes to
accumulate." t)
(register-definition-prefixes "test-cockpit" '("test-cockpit-"))


;;; Generated autoloads from test-cockpit-cargo.el

(register-definition-prefixes "test-cockpit-cargo" '("test-cockpit-cargo-"))


;;; Generated autoloads from test-cockpit-cask.el

(register-definition-prefixes "test-cockpit-cask" '("test-cockpit-cask-"))


;;; Generated autoloads from test-cockpit-eldev.el

(register-definition-prefixes "test-cockpit-eldev" '("test-cockpit-eldev-"))


;;; Generated autoloads from test-cockpit-mix.el

(register-definition-prefixes "test-cockpit-mix" '("test-cockpit-mix--"))


;;; Generated autoloads from test-cockpit-npm-jest.el

(register-definition-prefixes "test-cockpit-npm-jest" '("test-cockpit-npm-jest--"))


;;; Generated autoloads from test-cockpit-python.el

(register-definition-prefixes "test-cockpit-python" '("test-cockpit-"))

;;; End of scraped data

(provide 'test-cockpit-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; test-cockpit-autoloads.el ends here
